name:                synthesis-toy
version:             0.1.0.0
synopsis:            A toy version of synthesis to illustrate both the use of
                     unsatcores and incrementality in SBV.
# description:
github:              rohit507/sbv-synthesis-toy
license:             BSD3
author:              Rohit Ramesh
maintainer:          Rohit507@gmail.com
copyright:           2017 Rohit Ramesh
category:            Other
extra-source-files:
  - README.md

default-extensions:
  - GADTs
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - DeriveDataTypeable
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveFunctor
  - DuplicateRecordFields
  - RecordWildCards
  - NamedFieldPuns
  - TypeApplications
  - ApplicativeDo
  - ViewPatterns
  - TupleSections
  - StandaloneDeriving
  - ExplicitForAll
  - ScopedTypeVariables
  - TemplateHaskell
  - FunctionalDependencies
  - PatternGuards
  - RankNTypes
  - ConstraintKinds

dependencies:
  - base >= 4.7 && < 5
  - sbv
  - mtl
  - containers
  - newtype
  - lens

executables:
  synthesis-toy:
    source-dirs:      src
    main:             Main.hs
    other-modules:
      - Types
      - API
      - Input
      - Synthesis
      - Extract
