name:                synthesis-toy
version:             0.1.0.0
synopsis:            A toy version of synthesis to illustrate both the use of
                     unsatcores and incrementality in SBV.
# description:
github:              rohit507/sbv-synthesis-toy
license:             BSD3
author:              Rohit Ramesh
maintainer:          Rohit507@gmail.com
copyright:           2017 Rohit Ramesh
category:            Other
extra-source-files:
  - README.md

default-extensions:
  - ApplicativeDo
  - ConstraintKinds
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DuplicateRecordFields
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLists
  - PatternGuards
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - recursion-schemes
  - unordered-containers

library:
  source-dirs: lib

executables:
  edg-toy:
    source-dirs:
      - lib
      - app
    main:             Main.hs
